export const Questions = [
    { question:"Which of the following mammals can't jump?" , 
      optionA:"Dog" ,
      optionB:"Elephant" ,
      optionC:"Goat" ,
      optionD:"Lion" ,
      answer:"Elephant" ,
      

    },
    {
      question: "What insects can chew through wood and destroy your home?",
      optionA: "Ants",
      optionB: "Termites",
      optionC:"Lice" ,
      optionD:"Bed bugs" ,
      answer:  "Termites",
    },
    {
      question: " How long is a fortnight?",
      optionA: "15 days" ,
      optionB: "21 days" ,
      optionC: "7 days",
      optionD: "14 days" ,
      answer: "14 days" ,
    },
    {
      question:" Which of these tools do you use to change a car tyre?" ,
      optionA: "Jack",
      optionB: "Wrench",
      optionC: "Screwdriver",
      optionD: "Axle tie",
      answer:"Jack" ,
    },
    {
      question:"What is the full form of the medical procedure CPR?" ,
      optionA: "Cardiovascular Pressure Rescue",
      optionB:"Cardiovascular Pressure Repetition" ,
      optionC: "CXardiopulmonary Repetition",
      optionD:"Cardiopulmonary Resuscitation" ,
      answer:"Cardiopulmonary Resuscitation" ,
    },
    {
      question: "Which of these words doesn't have a rhyming word?",
      optionA:"Apple" ,
      optionB: "Cone",
      optionC: "Silver",
      optionD: "Lead",
      answer: "Silver",
    },
    {
      question:"What does a Barometer measure?" ,
      optionA:"Humidity" ,
      optionB: "Water Level",
      optionC: "Dew",
      optionD: "Atmospheric Pressure",
      answer: "Atmospheric Pressure",
    },
    {
      question: "Which of these is used to start a fire?",
      optionA: "Flint",
      optionB: "Granite",
      optionC: "Sandstone",
      optionD: "Marble",
      answer: "Flint",
    },
    {
      question:"'Exposure' in photography refers to which function of the camera?" ,
      optionA:"White Balance" ,
      optionB: "Amount of Light",
      optionC: "Shutter Speed",
      optionD: "Aperture",
      answer: "Amount of Light",
    },
    {
      question:"How many birthdays does the average person have?" ,
      optionA: "One",
      optionB: "Sixty",
      optionC: "Fifty",
      optionD: "Ten",
      answer:"One" ,
    },
    {
      question: "Some months have 31 days but how many have 28 days",
      optionA:"1" ,
      optionB: "0",
      optionC: "12",
      optionD: "6",
      answer: "12",
    },
    {
        question: "Before Mount Everest was discovered, what was the highest mountain on earth?",
        optionA:"Mount Abu" ,
        optionB: "K2 Peak",
        optionC: "Mount Everest",
        optionD: "Mount Carmel",
        answer: "Mount Everest",
      },
      {
        question:"What is the world's most populous country?" ,
        optionA:"China" ,
        optionB: "India",
        optionC: "USA",
        optionD: "Russia",
        answer: "China",
      },
      {
        question:"Which Of These Things CAN Disinfect A Wound?" ,
        optionA: "Smoke",
        optionB: "Vodka",
        optionC: "Mercury",
        optionD: "Pine Needles",
        answer: "Vodka",
      },
      {
        question: "When Buying Stocks, You Should Buy Low And Sell ______",
        optionA: "High",
        optionB: "Low",
        optionC: "Immediately",
        optionD: "Same Price",
        answer: "High",
      }
  ];